import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { ArrowRight, TrendingUp, Calendar, Target } from 'lucide-react';
import PageContainer from '../components/layout/PageContainer';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import DifficultyBadge from '../components/shared/DifficultyBadge';
import FastExercise from '../components/dashboard/FastExercise';
import HintsFeed from '../components/dashboard/HintsFeed';
import DailyFlowGraph from '../components/dashboard/DailyFlowGraph';
import ContributionCalendar from '../components/dashboard/ContributionCalendar';
import { useExerciseStore } from '../store/exerciseStore';
export default function Dashboard() {
    const { exercises, completedExerciseIds } = useExerciseStore();
    const featuredExercises = exercises.slice(0, 3);
    const recentCompleted = completedExerciseIds.slice(-3).reverse();
    // Select a random quick exercise (aim for fast, beginner-friendly)
    const quickExercises = exercises.filter((e) => e.durationMinutes <= 5);
    const quickExercise = quickExercises[Math.floor(Math.random() * quickExercises.length)] || exercises[0];
    return (_jsxs(PageContainer, { children: [_jsxs("div", { className: "mb-12", children: [_jsxs("h1", { className: "text-4xl md:text-5xl font-bold text-text-primary mb-4", children: ["Good morning.", ' ', _jsx("span", { className: "bg-gradient-to-r from-accent-primary to-accent-secondary bg-clip-text text-transparent", children: "Let's move." })] }), _jsx("p", { className: "text-lg text-text-secondary max-w-2xl mb-6", children: "Desk work builds posture problems. Break the cycle with guided exercises and ergonomic knowledge." }), _jsxs("div", { className: "flex gap-4", children: [_jsx(Link, { to: "/exercises", children: _jsx(Button, { children: "Start Moving" }) }), _jsx(Link, { to: "/wiki", children: _jsx(Button, { variant: "secondary", children: "Learn More" }) })] })] }), _jsxs("div", { className: "mb-12", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h2", { className: "text-2xl font-bold text-text-primary", children: "Featured Exercises" }), _jsx(Link, { to: "/exercises", className: "text-accent-primary hover:underline text-sm font-medium", children: "View All" })] }), _jsx("div", { className: "grid md:grid-cols-3 gap-6", children: featuredExercises.map((exercise) => (_jsx(Link, { to: `/exercises/${exercise.id}`, children: _jsxs(Card, { className: "h-full hover:shadow-card-hover transition-shadow", children: [_jsx("div", { className: "w-full aspect-video bg-gradient-to-br from-accent-primary to-accent-secondary rounded-card mb-4 flex items-center justify-center text-white", children: _jsx("img", { src: `https://i.ytimg.com/vi/${exercise.youtubeId}/hqdefault.jpg`, alt: exercise.name, className: "w-full h-full object-cover rounded-card", onError: (e) => {
                                                e.target.style.display = 'none';
                                            } }) }), _jsx("h3", { className: "font-bold text-lg text-text-primary mb-2", children: exercise.name }), _jsx("p", { className: "text-sm text-text-secondary mb-4 line-clamp-2", children: exercise.shortDescription }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(DifficultyBadge, { difficulty: exercise.difficulty }), _jsxs("span", { className: "text-xs text-text-secondary", children: [exercise.durationMinutes, " min"] })] })] }) }, exercise.id))) })] }), recentCompleted.length > 0 && (_jsxs("div", { className: "mb-12", children: [_jsxs("h2", { className: "text-2xl font-bold text-text-primary mb-6 flex items-center gap-2", children: [_jsx(TrendingUp, { className: "w-6 h-6 text-accent-secondary" }), "Recent Activity"] }), _jsx(Card, { children: _jsx("div", { className: "space-y-3", children: recentCompleted.map((exerciseId) => {
                                const exercise = exercises.find((e) => e.id === exerciseId);
                                return exercise ? (_jsxs(Link, { to: `/exercises/${exerciseId}`, className: "flex items-center justify-between p-3 hover:bg-gray-50 rounded-card transition-colors", children: [_jsx("span", { className: "text-text-primary font-medium", children: exercise.name }), _jsx(ArrowRight, { className: "w-5 h-5 text-accent-primary" })] }, exerciseId)) : null;
                            }) }) })] })), _jsxs("div", { className: "mb-12", children: [_jsx("h2", { className: "text-2xl font-bold text-text-primary mb-6", children: "\u26A1 5-Minute Quick Exercise" }), _jsx(FastExercise, { exercise: quickExercise })] }), _jsx("div", { className: "mb-12", children: _jsx(HintsFeed, { exercises: exercises }) }), _jsxs("div", { className: "grid md:grid-cols-3 gap-6 mb-12", children: [_jsx(Card, { children: _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-3xl font-bold text-accent-primary", children: exercises.length }), _jsx("p", { className: "text-text-secondary text-sm mt-2", children: "Total Exercises" })] }) }), _jsx(Card, { children: _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-3xl font-bold text-accent-secondary", children: completedExerciseIds.length }), _jsx("p", { className: "text-text-secondary text-sm mt-2", children: "Completed" })] }) }), _jsx(Card, { children: _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-3xl font-bold text-accent-primary", children: "5" }), _jsx("p", { className: "text-text-secondary text-sm mt-2", children: "Wiki Articles" })] }) })] }), _jsxs("div", { className: "mb-12", children: [_jsxs("h2", { className: "text-2xl font-bold text-text-primary mb-6 flex items-center gap-2", children: [_jsx(Target, { className: "w-6 h-6 text-accent-primary" }), "Today's Flow"] }), _jsx(DailyFlowGraph, {})] }), _jsxs("div", { children: [_jsxs("h2", { className: "text-2xl font-bold text-text-primary mb-6 flex items-center gap-2", children: [_jsx(Calendar, { className: "w-6 h-6 text-accent-secondary" }), "Your Progress"] }), _jsx(Card, { className: "p-6", children: _jsx(ContributionCalendar, {}) })] })] }));
}
