import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Play, Clock } from 'lucide-react';
import Card from '../ui/Card';
import DifficultyBadge from '../shared/DifficultyBadge';
export default function FastExercise({ exercise }) {
    return (_jsx(Link, { to: `/exercises/${exercise.id}`, children: _jsxs(Card, { className: "overflow-hidden hover:shadow-card-hover transition-shadow h-full", children: [_jsxs("div", { className: "relative w-full aspect-video bg-gradient-to-br from-accent-primary to-accent-secondary rounded-card mb-4 overflow-hidden flex items-center justify-center", children: [_jsx("img", { src: `https://i.ytimg.com/vi/${exercise.youtubeId}/hqdefault.jpg`, alt: exercise.name, className: "w-full h-full object-cover", onError: (e) => {
                                e.target.style.display = 'none';
                            } }), _jsx("div", { className: "absolute inset-0 flex items-center justify-center bg-black bg-opacity-0 group-hover:bg-opacity-30 transition-all", children: _jsx(Play, { className: "w-12 h-12 text-white opacity-70", fill: "currentColor" }) })] }), _jsxs("div", { children: [_jsx("div", { className: "flex items-start justify-between gap-2 mb-2", children: _jsx("h3", { className: "font-bold text-lg text-text-primary flex-1", children: exercise.name }) }), _jsx("p", { className: "text-sm text-text-secondary mb-4 line-clamp-2", children: exercise.shortDescription }), _jsxs("div", { className: "flex items-center justify-between gap-2 flex-wrap", children: [_jsxs("div", { className: "flex items-center gap-2 text-xs text-text-secondary", children: [_jsx(Clock, { className: "w-4 h-4" }), _jsxs("span", { children: [exercise.durationMinutes, " min"] })] }), _jsx(DifficultyBadge, { difficulty: exercise.difficulty })] })] }), _jsx("div", { className: "mt-4 pt-4 border-t border-gray-200", children: _jsxs("div", { className: "text-xs text-accent-primary font-medium flex items-center gap-1", children: [_jsx(Play, { className: "w-3 h-3" }), "Start Exercise"] }) })] }) }));
}
